defaults:
  - db: credentials-rlaidb
  - schema: default-schema
  - agent: ppo
  - policy: gaussian
  - agent/sweeper_params@hydra.sweeper.params: sac_sweeper_md_sanity
  - override hydra/launcher: submitit_local
  - override hydra/job_logging: default
  - _self_

args:
  run: 1000000
  db_prefix: hshah1
  db_name: 70x_testttt11
  seed: 0
  steps: 5000
  n_actions: 3
  action_min: 0
  action_max: 20
  n_threads: 1
  cuda: False
  noise: 0.01

# do a sweep with these settings by doing python main.py -m
hydra:
 output_subdir: null
 sweep:
   dir: ${hydra.runtime.cwd}/hydra_sweeps
   subdir: ${hydra.job.name}/${hydra.job.num}
# mode: MULTIRUN
 launcher:
   submitit_folder: ${hydra.sweep.dir}/.submitit/%j
   name: ${hydra.job.name}
   timeout_min: 119
   nodes: 1
   tasks_per_node: 10
   cpus_per_task: 1
   gpus_per_node: null
 sweeper:
   params:
     args.seed: range(0,10)
#     agent/actor: heavytailed_gaussian, q_gaussian, gaussian, beta, student
#     agent/actor: glob(*) # sweep over all policies
