defaults:
  - base_common
  - _self_

name: sac

# actor
actor_lr: 0.05
actor_lr_multiplier: 1
n_actor_updates: 1
n_action_proposals: 30
n_action_proposals_selected: 3

# SAC knobs
entropy_coef: 0.01
value_baseline_lr: 0.1

